server:
  port: 8888

spring:
  application:
    name: gateway-service
  cloud:
    discovery:
      enabled: true
#    gateway:
#      routes:
#        - id: r1
#          uri: https://localhost:8081
#          predicates:
#            - Path=/customers/**
#        - id: r2
#          uri: https://localhost:8082
#          predicates:
#            - Path=/products/**
